[package]
name = "staging-node-cli"
version = "3.0.0-dev"
authors.workspace = true
description = "Generic Substrate node implementation in Rust."
build = "build.rs"
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
default-run = "substrate-node"
homepage = "https://substrate.io"
repository.workspace = true
publish = false

[lints]
workspace = true

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[badges]
maintenance = { status = "actively-developed" }
is-it-maintained-issue-resolution = { repository = "paritytech/polkadot-sdk" }
is-it-maintained-open-issues = { repository = "paritytech/polkadot-sdk" }

[[bin]]
name = "substrate-node"
path = "bin/main.rs"
required-features = ["cli"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# External dependencies:
array-bytes = "6.1"
clap = { version = "4.5.3", features = ["derive"], optional = true }
codec = { package = "parity-scale-codec", version = "3.6.1" }
serde = { features = ["derive"], workspace = true, default-features = true }
jsonrpsee = { version = "0.22", features = ["server"] }
futures = "0.3.30"
log = { workspace = true, default-features = true }
rand = "0.8"
serde_json = { workspace = true, default-features = true }

# The Polkadot-SDK:
polkadot-sdk = { path = "../../../../umbrella", features = ["node"] }

# Shared code of the staging-node:
kitchensink-runtime = { path = "../runtime" }
node-rpc = { path = "../rpc" }
node-primitives = { path = "../primitives" }
node-inspect = { package = "staging-node-inspect", path = "../inspect", optional = true }

[dev-dependencies]
futures = "0.3.30"
tempfile = "3.1.0"
assert_cmd = "2.0.2"
nix = { version = "0.27.1", features = ["signal"] }
regex = "1.6.0"
platforms = "3.0"
soketto = "0.7.1"
criterion = { version = "0.4.0", features = ["async_tokio"] }
tokio = { version = "1.22.0", features = ["macros", "parking_lot", "time"] }
tokio-util = { version = "0.7.4", features = ["compat"] }
wait-timeout = "0.2"
wat = "1.0"
serde_json = { workspace = true, default-features = true }
scale-info = { version = "2.11.1", features = ["derive", "serde"] }

node-testing = { path = "../testing" }

substrate-cli-test-utils = { path = "../../../test-utils/cli" }
sc-service-test = { path = "../../../client/service/test" }

[build-dependencies]
clap = { version = "4.5.3", optional = true }
clap_complete = { version = "4.0.2", optional = true }

node-inspect = { package = "staging-node-inspect", path = "../inspect", optional = true }

polkadot-sdk = { path = "../../../../umbrella", features = ["substrate-build-script-utils", "sc-cli", "sc-storage-monitor", "frame-benchmarking-cli"], optional = true }

[features]
default = ["cli"]
cli = [
	"clap",
	"clap_complete",
	"node-inspect",
	"polkadot-sdk",
]
runtime-benchmarks = [
	"kitchensink-runtime/runtime-benchmarks",
	"node-inspect?/runtime-benchmarks",
	"polkadot-sdk/runtime-benchmarks",
]
try-runtime = [
	"kitchensink-runtime/try-runtime",
	"polkadot-sdk/try-runtime",
	"substrate-cli-test-utils/try-runtime",
]

[[bench]]
name = "transaction_pool"
harness = false

[[bench]]
name = "block_production"
harness = false

[[bench]]
name = "executor"
harness = false
